### ISSUE TITLE
Go to Definition not working for YAML scalar types and scalar indicators

### ISSUE THREAD

**Issue by pavlitsky** [shanehofstetter/rails-i18n-vscode#15]
`Go to Definition` doesn't work for YAML syntax other than single strings. Not sure all of below needed, cited it just for note. I personally miss multiline strings with scalar indicators that occur quite often if you limited string length in the editor. It would be great to add `Go to Definition` support for them.

```yaml
  # Multiline strings with scalar indicators, chomp modifiers, and both
  foo1: >
    Import successfully completed. %{created} lines added. %{updated} lines updated.
    %{removed} lines removed.
  foo2: >-
    Foo 2
  foo3: >+
    Foo 3
  foo4: |
    Foo 4
  foo5: |-
    Foo 5
  foo6: |+
    Foo 6
  # Dashed key name
  foo-7: Foo 7
  # Scalar types: Boolean
  foo8: false
  foo9: true
  # Scalar types: Numeric
  foo10: 8
  foo11: 9.9
  foo12: 0x1fff
  foo13: 12.3456e+03
  foo14: 07654
  # Scalar types: NAN
  foo15: .inf
  foo16: -.Inf
  foo17: .NAN
  # Scalar types: Null value
  foo18: null
```
