### ISSUE TITLE
Lazy lookup in rails controllers

### ISSUE THREAD

**Issue by valter0ff** [shanehofstetter/rails-i18n-vscode#33]
Thank you so much for this nice extension. It works like a charm.
In views it can handle lazy lookup like `t('.title')`

But can't resolve it for controllers:
this will work `t('home.menu.index.title')`
but this no `t('.title')`
```yml

en:
  home:
    menu:
      index:
        title: My title
```
